server:
  host: 127.0.0.1
  port: 8088
mysql:
  hostname: localhost
  config: charset=utf8mb4&parseTime=True&loc=Local
  port: 3306
  username: root
  password: 123456
  database: go_web
zap:
  level: info
  prefix: "[golang] "
  format: console
  director: logs
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true